{% set name = "Vose-Alias-Method" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7fc47de865d0b407adb035043a7e89cb8a5d1822c76e1eb308ef48b172ae3e48

build:
  number: 0
  noarch: python
  entry_points:
    - vose-sampler=vose_sampler.vose_sampler:main
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7

test:
  imports:
    - vose_sampler
  commands:
    - vose-sampler --help

about:
  home: https://github.com/asmith26/Vose-Alias-Method.git
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python implementation of Vose's alias method, an efficient algorithm for sampling from a discrete probability distribution.
  doc_url: https://github.com/asmith26/Vose-Alias-Method/blob/master/README.md#example-usage
  dev_url: https://github.com/asmith26/Vose-Alias-Method

extra:
  recipe-maintainers:
    - asmith26
