travis:
  secure:
    BINSTAR_TOKEN: qkaSc9gJTQ1EEu5uWqQvRCdz2ogC41uQ4QSabn+uLdVkuWvFxsXgRcDN32c28hMKmdKAfbmzUmrC+8ZZuefpJ89lB8KpyoeZHCF/WU6cPeT7UVRwEfTNIy8vT64Y/WjcQsfkcSr8kplCFOeNYN+tfPQ4Ryb6nnqIH9YD3jxG6EHEL+gckgu1gxxwxHhDRGW6tq+a+5S1Jb/jgmxnLlarS+fK42zehaFOpzfVOt8xD9SOh4RC0l73SZgITu0on7zulOCRwh4tSBvQLic4C2akfkguJX8M4hya+yJ+3IhcBjdyNgywEmirKpYNy8I9S7BGM0jwZYyRcLLHGuUF3TL2Jczfcd+Wj8iYqZ3BXN4m2DiB1k/mwjoBp7h2eg4gnZmncQlbSmVN8N5r/ZPCesTNV2Igf6k3FXv1k94qJBNyS/Uo+FISC4B/exFLyWIg3eWxNMq5Jit+UZrDcxsypQNwN3kE0P81QJA3gRT11M1Sj5j3Z7lngo3Jil+mdXgijaoatJ4bYUeO5p40UhA/jAcsAw5AxTMb9FXSGohFmbE2d9qV6Wk0za7UomDMin58PQJN5HczBEizpwussBrHcQZF8erJvjMWSoMeFHAo3nrOJqgx9UhniDk0WdsGFtGr7QzeqTYYhNc3+F4eSnjrjYaw68YXczpqlmwdjz8+7KFE/tg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
