travis:
  secure:
    BINSTAR_TOKEN: a9fYwT4H77/L3U9Ay13usFWSuP6syO18XWhHe9ycd0dhWKDjs4WqcUogKEV3sXipFsB0geGLlILn1wdjORrkgSYE9AAkq63tWoJ1V/igJBHWE4wVtB1YBujtgrF7STYG7304UV8maf2KzQhovyCbfR+AwpBlCMR1kbj920KWLRtCZQE0+Ih5zxKwv6iQgtpdTmbLgAkuVwjmSOla/W5hhJanNoVI68E0ynx/X4QRZAA0FBLwB/YelAnQPyacC4WU68bauAyrvRD6YrVNe1EeOsMaUh312xmp0aBLtvWzuQTvyXR4RjlWXeji3O1hLZZwICmaBqfxzEk8QG+d6RO4W9eGz27NZxbRudkjq0Up8hJnw50lM3wXXl0bqlu20TPS7WvvqvkIl6dzpkDEwILXYCvY2GgIMdbpFA8MV69hflI0oO4F/KJLRzSZd8OdERGIkljfX/6l31x4yX8G1Xqx3ZXxo4pTW3siYXP8bAMe7BDy97/WONd2dHHyEFLHUST96PP62IK8MfBPl+wE0NL8jrluZGouai0Xx/LaMbl7RCCZRcYTSgO2IbsbVfOQsET4acrhQWxwKgbJdctHOyn8V4n3MvZ7Cxyqphjhu+NAOoi7SYPmsm1jldO3dkjvgTOSE21y/AX6rIt1JqGZf0kQf88NjDAXfwAw5eb+qUuIvyk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
